### ISSUE TITLE
Add office addresses to the contact page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/canonical.com#107]

**Comment by anthonydillon** [comment]
Please add the following addresses to the contact us page:

## Where we are
London, United Kingdom

Canonical Group Limited
5th Floor, Blue Fin Building
110 Southwark Street
London, SE1 0SU
United Kingdom
View map ›
Austin, United States

Canonical USA Inc.
Link Flex
2301 W Anderson Ln
Austin, TX 78757
United States of America
View map ›
Boston, United States

Canonical USA Inc.
18 Tremont Street
Suite 210
Boston, MA 02108
United States of America
View map ›
Shanghai, China

Room 1246, 12F
No. 331 North Caoxi Road
Shanghai 200031
China
上海市漕溪北路331号12楼1246室 200031
View map ›
Beijing, China

Unit 1118-19, Level 11, China World Office 1
1 Jianguomenwai Avenue, Chaoyang District, Beijing
Beijing P.R.C. 100004
China
北京市朝阳区建国门外大街1号国贸写字楼1座11层1118-19室 100004
View map ›
Taipei, Taiwan

Canonical Limited Taiwan Branch
Room D, 46F,
No. 7, Xin Yi Rd., Sec.5,
Taipei 101
Taiwan
View map ›
Isle of Man

Canonical Limited
One Circular Road
Douglas
Isle of Man
IM1 1SB
View map ›
Japan

Canonical Limited
3rd Floor, Sanno Park Tower
2-11-1 Nagata-cho
Chiyoda-ku
Tokyo
100-6162
Japan
+81 3-6205-3075
View map ›

**Comment by waynecrosby** [comment]
@solazio Did anyone ask Ant to add the addresses or has he just asked you?

**Comment by solazio** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/926e2ff2-8f36-473a-8839-04155106dfb0)
