### ISSUE TITLE
Lorem ipsum job description on career game results

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/canonical.com#126]
Go to /careers/start and complete the game. Once you go to the results page see "lorem ipsum text" for job description.

**Comment by sowasred2012** [comment]
Looking at [the job object returned by the API](https://developers.greenhouse.io/job-board.html#retrieve-a-job), the closest thing to a description we could use is under `content`, which is the entire job posting, and contains a lot of HTML markup.

Stripping out those tags, in order for them not to interfere with the layout, we end up with something a bit rough and ready, like this:

![Screenshot 2019-12-19 at 17 18 48](https://user-images.githubusercontent.com/2376968/71194352-aefb8200-2283-11ea-85ef-2a399358586d.png)

Should we go with this, or could we drop this bit of copy? The API doesn't appear to offer a short description we could use.

**Comment by solazio** [comment]
@sowasred2012 I think you should just hide it for now. Like we do if you go to /careers/sales#available-roles.
