### ISSUE TITLE
Very large images in use

### ISSUE THREAD

**Issue by sowasred2012** [canonical-web-and-design/canonical.com#135]
Haven't checked the rest of the site, but found that /careers and /careers/lifestyle both load very large images:

![Screenshot 2019-12-20 at 13 34 37](https://user-images.githubusercontent.com/2376968/71258274-af505780-232d-11ea-802c-01dd55d84eb5.png)
![Screenshot 2019-12-20 at 13 32 38](https://user-images.githubusercontent.com/2376968/71258277-b0818480-232d-11ea-8cd7-79648507f7bb.png)

**Comment by waynecrosby** [comment]
Hey @sowasred2012 
I've uploaded some smaller files for the above, I've kept the file names similar so they are easy to track:
https://assets.ubuntu.com/v1/5c69a4be-AdobeStock_193792692.jpg (128KB)
https://assets.ubuntu.com/v1/5d35895c-cities2.jpg (121KB)
https://assets.ubuntu.com/v1/f08c945e-canonical-travel.jpg (158KB)

I don't know how the images have been added into the code but below are some that are physically closer to the actual size:
https://assets.ubuntu.com/v1/6bec28d5-canonical-careers-sized.jpg
https://assets.ubuntu.com/v1/37d19b8c-cities-sized.jpg
https://assets.ubuntu.com/v1/08281090-canonical-travel-sized.jpg

Let me know if you need anything else.
