### ISSUE TITLE
Add meta image screenshot of gamification

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/canonical.com#151]
[As per Thibaut's request](https://docs.google.com/document/d/1JEJaOghggrocxnRCoTrJMCg_z_xD9n6xBSnovcX3HMg/edit?ts=5e1f4d47#heading=h.kcsmaipo87ml):
Can we add a screenshot of the gamified page as a meta image so we can share it on social and see the image/gamification element.

**Comment by SirSamTumless** [comment]
@steverydz @deadlight @anthonydillon Could one of you please jump on this - Thibaut's flagged it as an issue.

**Comment by steverydz** [comment]
I'll take a look
