### ISSUE TITLE
The last careers department do not load

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/canonical.com#155]
The last item in the `career_department` set does not load the feed. I have added a dummy last item to mask the issue but this should be fix properly:
https://github.com/canonical-web-and-design/canonical.com/blob/master/webapp/app.py#L44

**Comment by sowasred2012** [comment]
@nottrobin added a [fix for this](https://github.com/canonical-web-and-design/canonical.com/commit/950a31596d2e29f56800813cb3de1c480c577e05); closing this issue.
