### ISSUE TITLE
Implement WKD (Web Key Directory) of OpenPGP keys

### ISSUE THREAD

**Issue by Mikaela** [canonical-web-and-design/canonical.com#187]
> Web Key Directories provide an easy way to discover public keys through HTTPS. They provide an important piece to the infrastructure to improve the user experience for exchanging secure emails and files.
> 
> In contrast to the public keyservers a Web Key Directory does not publish mail addresses. And it is an authoritative pubkey source for its domain. 

* https://wiki.gnupg.org/WKD

I am not sure if this is the correct place to request this, but due to the [certificate flooding attacks](https://dkg.fifthhorseman.net/blog/openpgp-certificate-flooding.html) I have been using [keys.openpgp.org](https://keys.openpgp.org/) as my keyserver and a lot of people from Canonical haven't [uploaded/confirmed their keys there](https://keys.openpgp.org/upload) resulting to an error from Enigmail when I try to verify signatures in Ubuntu security mailing list.

When that happens I run `gpg --auto-key-locate nodefault,wkd --locate-keys <name>@canonical.com` (I have an alias) which results to "No data" error, while with `@debian.org` addresses I receive the key as [they have implemented WKD](https://dkg.fifthhorseman.net/blog/wkd-for-debian.org.html). After this I have to fall back to using `keyserver.ubuntu.com` which as far as I understand has no precautions against certificate flooding attacks (I am happy to hear if I am wrong) taking the risk of encountering a flooded certificate and leading to excess resource usage and gpg not working.

Implementing WKD would also result to WKD-capable email clients automatically encrypting emails to users with OpenPGP keys when composing emails.

This issue also affects Ubuntu.com, but I haven't had to search for public keys of `@ubuntu.com` addresses yet.

**Comment by tbille** [comment]
@Mikaela Hey, thanks for notifying this. This repository is for the site [canonical.com](https://canonical.com).

Could you send an email at this address: rt@admin.canonical.com to explain what is your issue? The team that takes care of that will be way more qualified to answer to those questions :smile: 

I am closing the issue for now.
