### ISSUE TITLE
Improve drop-down menu to look like ubuntu.com

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/canonical.com#207]
Currently when you click on `Partners` in the nav bar, the drop-down menu has a white bar at the bottom, instead of overlaying over the page content like it does on https://ubuntu.com 
Also the scroll bar on the right should be hidden

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/5cbbc12f-07b2-4815-bd92-9a65cb6c0cf1)

![image.png](https://images.zenhubusercontent.com/5cb4608f97df763a9090bdec/50efffdf-4ef7-437a-b1bc-8f128b595c55)

**Comment by SirSamTumless** [comment]
Needs a view design.

**Comment by steverydz** [comment]
This doesn't use a dropdown anymore. Closing
