### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by polynombre** [canonical-web-and-design/canonical.com#226]
Using Firefox 75.0:
I go to https://canonical.com/
Scroll to bottom, click on "Projects"
If I then click on "Products" or "Careers" I get a 404.
If I first click on Products and then on Careers I even get an empty page.

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to report this issue. We will get a fix out for this as quickly as possible,

**Comment by steverydz** [comment]
Fixed in https://github.com/canonical-web-and-design/canonical.com/pull/229
