### ISSUE TITLE
people.canonical.com http->https redirection encodes already encoded get params

### ISSUE THREAD

**Issue by obfusk** [canonical-web-and-design/canonical.com#227]
This is probably not the right place to report this, but since I was unable to find out where to report bugs against `people.canonical.com`, I'm hoping you can point me in the right direction.

See https://github.com/psf/requests/issues/5077 for details.

**Comment by pmahnke** [comment]
@obfusk thanks for filing this.

I am not sure where it belongs either, so I have sent it to our IS team.  RT#125911

**Comment by pmahnke** [comment]
@obfusk Good news I hope.

I got this back from our IS team:


> I have modified the redirect adding NoEscape[1] to it and that seems to have fixed the issue.
> 
> [1]https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_ne
> 
> Thanks,
> ---------------------
> Alexandre

Let me know if that fixed things.  Re-open th issue if not.

Peter

**Comment by obfusk** [comment]
Seems to be fixed indeed. Thanks.
