### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by mlk71075** [canonical-web-and-design/canonical.com#231]
Wiki at https://wiki.ubuntu.com/UEFI/SecureBoot/KeyManagement/KeyGeneration, section 3 shows this: http://www.canonical.com/secure-boot-master-ca.crl which in turn gives the 404 error.

**Comment by pmahnke** [comment]
@mlk71075 thank you for reporting this.  We somehow lost the file in our upgrade of canonical.com.

I have put in a PR to put it back.

Thanks!

**Comment by pmahnke** [comment]
#233 fixes this... so closing.
