### ISSUE TITLE
Bug in Jobs Page.

### ISSUE THREAD

**Issue by wortforfilms** [canonical-web-and-design/canonical.com#253]
Looks like your job page in not working. Will love to help fixing it.

**Comment by anthonydillon** [comment]
Could you provide more detail on the bug you have discovered? We would be happy to happy you provide a fix.

**Comment by wortforfilms** [comment]
https://canonical.com/careers/2095959?utm_source=ubunteu&utm_medium=url_shortner&utm_term=dev-jobs&utm_campaign=shortner

this redirects to 404 not found from ubuntu site. 
#

**Comment by anthonydillon** [comment]
Oh I see, where did you find this link? This is likely as the position has been closed. I agree it would be nice to display that message.
