### ISSUE TITLE
Additional (unrequired) text in the Desktop Programme page

### ISSUE THREAD

**Issue by pieqq** [canonical-web-and-design/canonical.com#259]
In the [Desktop Programme page](https://canonical.com/partners/desktop), there seem to be a piece of text that doesn't belong here:

![image](https://user-images.githubusercontent.com/512471/88022573-1bb06500-cb62-11ea-8383-47b2bb1d699c.png)

Under “Works out of the box”, I think the following text can be removed:

>  Information about Canonical. Canonical produces Ubuntu, provides commercial services for enterprise users, and works with industry partners on delivery and certification.

**Comment by pmahnke** [comment]
@pieqq thank you... you are entirely correct, that must have been a random paste.
