### ISSUE TITLE
Application Form Limit is too low

### ISSUE THREAD

**Issue by devLeopar** [canonical-web-and-design/canonical.com#269]
I tried to submit to form as link below but the server returned http 413 code as "entity is too much". I don't know what is allowed size of the files but CVs are usually more than 1MB

Can you change it ? Here is the link of the respected form : https://canonical.com/careers/2274212

**Comment by anthonydillon** [comment]
@devLeopar thank you very much for taking the time to report this issue to us. You are correct, the limit is 1MB which we should address in two-fold. 
1. Let the user know via form help text when the limit is
2. Try and raise the limit to something more reasonable

**Comment by devLeopar** [comment]
Hi Anthony;

I applied to Job that I've mentioned to you on previous email. Have you had
a chance to forward it to HR ? If you remember, I also sent you you my
application screenshot since I could not fill the form due to this
limitation.

Thank you
Oktar

Anthony Dillon <notifications@github.com>, 12 Ağu 2020 Çar, 19:00 tarihinde
şunu yazdı:

**Comment by anthonydillon** [comment]
Ah I'm sorry to hear that. Are you still experiencing the same problem?

I have filed an issue four the API limit:
https://github.com/canonical-web-and-design/canonical.com/issues/272

Thanks,
Anthony.

**Comment by anthonydillon** [comment]
@devLeopar thank you for your patience.

The underlying issue here is still valid and should be remedied.
