### ISSUE TITLE
Technical ops career page throws 404 when accessed from /careers

### ISSUE THREAD

**Issue by HristoMohamed** [canonical-web-and-design/canonical.com#280]
I tried a few times over the last days, so it is not probably a one time thing :) Happens when accessed from /careers landing page

<img width="1007" alt="Screenshot 2020-09-16 at 11 49 59" src="https://user-images.githubusercontent.com/3972628/93321726-cf586d00-f812-11ea-9f07-124b96ea445b.png">

**Comment by anthonydillon** [comment]
@HristoMohamed Thank you for taking the time to report this issue to us. The links have been updated. Sorry about that.
