### ISSUE TITLE
« Manage your tracker settings » link not working

### ISSUE THREAD

**Issue by Minteck** [canonical-web-and-design/canonical.com#296]
Title is pretty self-forward. The « Manage your tracker settings » link on the footer is not working, and just link to the current page, regardless of which page is currently loaded.

**Comment by anthonydillon** [comment]
@Minteck thank you for reporting this issue. Do you have JS disabled?

**Comment by anthonydillon** [comment]
@Minteck Oh strange, could you let me know what browser and version you are using? Do you still have the same issue?

**Comment by SirSamTumless** [comment]
Hi @Minteck - is this issue still occurring?

**Comment by Minteck** [comment]
The issue still occur. However, it doesn't occur when I use a private window, I suspect an add-on being the cause of the problem, I'll investigate on my side.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Minteck** [comment]
Finally, it was caused by uBlock Origin. Also, sorry for the kind of ad on the last reply, I forgot to change the default signature of my email app.
________________________________

**Comment by anthonydillon** [comment]
@Minteck thank you very much for reporting back your findings. I will investigate further and see if I can replicate.

**Comment by anthonydillon** [comment]
I honestly can't replicate this with uBlock on or off. So will close but it others find this an issue please reopen.
