### ISSUE TITLE
404: Page not found https://canonical.com/career/lifestyle

### ISSUE THREAD

**Issue by lee-vincent** [canonical-web-and-design/canonical.com#301]
[canonical-career-lifestyle.docx](https://github.com/canonical-web-and-design/canonical.com/files/5387331/canonical-career-lifestyle.docx)

**Comment by anthonydillon** [comment]
Scroll to the bottom and hit "Projects"
Then hit the Career link in the main menu
When the mega menu pulls down click Lifestyle at the bottom of it
See a 404

**Comment by anthonydillon** [comment]
Link should be /careers/lifestyle instead of /career/lifestyle

**Comment by pmahnke** [comment]
@lee-vincent thanks for filing this.
