### ISSUE TITLE
Integration forms between greenhouse and canonical careers website don't work anymore

### ISSUE THREAD

**Issue by lborda** [canonical-web-and-design/canonical.com#310]
Hello,

We have two roles available where the embedded greenhouse predefined form questions don't anymore. It shows in greenhouse as submitted but the data is not there. It used to work quite well.

Roles :
https://canonical.com/careers/1292730
https://canonical.com/careers/2402595

Can you fix and/or engage with greenhouse please?

**Comment by anthonydillon** [comment]
Thank you for reporting this issue. I have identified the issue and am working on a fix.
