### ISSUE TITLE
Update the new logo of Huawei

### ISSUE THREAD

**Issue by zprood** [canonical-web-and-design/canonical.com#315]
Hi, Huawei has sent the new design logo to us, the logo on /partners/ihv-and-oem page is out of date, can you help to update ?
Logo files link: [https://drive.google.com/drive/folders/1P50o507NqsGLAP2Yh_nK24pYN3GlstTd?usp=sharing](url)

Thanks.

**Comment by pmahnke** [comment]
I have fixed it, but partners have a database that Marketing can update these in.
