### ISSUE TITLE
Sort by is in a weird position

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/canonical.com#333]
The position of the "Sort by" filter is off

https://canonical.com/careers/results?coreSkills=Scientist,Designer,Developer,Manager,Tester

![image](https://user-images.githubusercontent.com/40214246/106050354-069f2a80-60df-11eb-9f80-be0a1b48007f.png)

**Comment by carkod** [comment]
You already filed this #322 Duplicate.
