### ISSUE TITLE
[c.c career enhancements] Add ability for roles to have multiple departments in greenhouse and use on c.c

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/canonical.com#352]
[Brief](https://docs.google.com/document/d/1eXlLZKLmq_tLrOCgulbT4KYhsCq3FZ8AA7KX7L2jMeY/edit#)

We would have to create a new custom field and then migrate the existing field to the multiselect one and update canonical.com to use this instead of the external department field (you cannot migrate the field type).

**Comment by goulinkh** [comment]
@pmahnke I just checked the list of vacancies, there are some one where the departments field is empty even thought it has the department field, for example: 

```
jobId:2426985, department:engineering, departments: []
``` 

Should we handle this case in the code where we use the department value ?

**Comment by pmahnke** [comment]
@goulinkh

> (you cannot migrate the field type)

means I had to create the new departments field rather than change the department field to allow multiselect in greenhouse.
