### ISSUE TITLE
Bad gateway (502) on careers website

### ISSUE THREAD

**Issue by dariakolarczyk-mkt** [canonical-web-and-design/canonical.com#361]
Hi!

After filling out the form on https://canonical.com/careers/start, I received an issue twice, after refreshing for the third time, it worked but I just thought you should know. In general, I love the thought and design of the website so it would be a shame to have that awesome impression ruined by the occasional bug.

Have a great day!

Daria

**Comment by carkod** [comment]
This looks like a Greenhouse API problem, but I haven't been able to reproduce it. Do we have rate limits for this API?
https://sentry.is.canonical.com/canonical/canonical-com/issues/16953/?query=is%3Aunresolved

**Comment by jpmartinspt** [comment]
@carkod we do. @pmahnke can we get in touch with greenhouse to see if they can increase the limit for our API key?

**Comment by jpmartinspt** [comment]
We have filed a case with Greenhouse to get a higher request limit and that will probably avoid future 502s once we get it. 
Thank you for taking the time to report this @dariakolarczyk-mkt.
