### ISSUE TITLE
CLA not available as a PDF

### ISSUE THREAD

**Issue by fcole90** [canonical-web-and-design/canonical.com#367]
At https://ubuntu.com/legal/contributors/agreement, there's a link for downloading the CLA as PDF, but it goes 404.

**Comment by anthonydillon** [comment]
@fcole90 Could you please try again. We might have had a short outage. Both documents work for me in the "Additional information" section.

**Comment by fcole90** [comment]
I still get the 404. Those are the links:
-  https://canonical.com/sites/default/files/active/images/Canonical-HA-CLA-ANY-I.pdf
- https://canonical.com/sites/default/files/active/images/Canonical-HA-CLA-ANY-E.pdf

The ones you mentioned work for me as well. The ones that don't are at the end of each agreement:

> 6.5 If any provision of this Agreement is found void and unenforceable, such provision will be replaced to the extent possible with a provision that comes closest to the meaning of the original provision and which is enforceable. The terms and conditions set forth in this Agreement shall apply notwithstanding any failure of essential purpose of this Agreement or any limited remedy to the maximum extent possible under law.
>
> To [download as a PDF](http://www.canonical.com/sites/default/files/active/images/Canonical-HA-CLA-ANY-I.pdf)

**Comment by anthonydillon** [comment]
@fcole90 thanks for the info. I have proposed a fix to the project. This should be live soon. If you need the documents now you can find them here:
- https://assets.ubuntu.com/v1/869aa215-Canonical-HA-CLA-ANY-I.pdf
- https://assets.ubuntu.com/v1/4dadfc6b-Canonical-HA-CLA-ANY-E.pdf

**Comment by fcole90** [comment]
Thanks, everything works now! 😃 👍
