### ISSUE TITLE
Canonical Company information

### ISSUE THREAD

**Issue by j-jeurissen** [canonical-web-and-design/canonical.com#374]
I would like to know more about canonical. Filosofie,  Who runs it etc.

**Comment by SirSamTumless** [comment]
Hi, What kind of information are you looking for? Have you looked at https://ubuntu.com/about and https://ubuntu.com/community - it has some information you might be interested in. Happy to help you with any questions you have.

**Comment by pmahnke** [comment]
No reply, so closing.  Reopen if you want to add more details to the request.
