### ISSUE TITLE
save color button

### ISSUE THREAD

**Issue by luismendes070** [canonical-web-and-design/canonical.com#376]
![Screenshot from 2021-04-02 11-59-06](https://user-images.githubusercontent.com/11665035/113427166-f63f5080-93aa-11eb-9255-07f5dc31d615.png)

**Comment by anthonydillon** [comment]
Sorry to hear you are having a problem with save buttons in Ubuntu. Unfortunately, we cannot provide support via this channel as this issue tracker is for canonical.com website.

If you could report a bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question as a topic on https://discourse.ubuntu.com/c/support-help-requests and you should receive a quick response.
