### ISSUE TITLE
Need to learn licensing if it is AGPL or GPL 

### ISSUE THREAD

**Issue by hwpplayer1** [canonical-web-and-design/canonical.com#381]
I need to learn licensing if it is AGPL or GPL

**Comment by SirSamTumless** [comment]
Hi - which thing do you want to know the license of?

**Comment by hwpplayer1** [comment]
https://github.com/canonical-web-and-design/www.canonical.com/blob/master/LICENSE.md it says that the project is licensed under the terms of GPL version 3 ( or maybe any later ) so it should be same or AGPL maybe 

Thanks

**Comment by SirSamTumless** [comment]
You are referencing the license of the Canonical website, would you mind letting me know what actual project you are looking at the license for?

**Comment by hwpplayer1** [comment]
https://github.com/canonical-web-and-design/canonical.com and the old web https://github.com/canonical-web-and-design/www.canonical.com/

**Comment by fitojb** [comment]
Since this repo lacks a license file, I think it’s safe to assume it’s [source-available](https://en.wikipedia.org/wiki/Source-available_software) but not open source (i.e. proprietary).

**Comment by pmahnke** [comment]
@hwpplayer1 it should have had the same as ubuntu.com

> ## License
> The content of this project is licensed under the Creative Commons Attribution-ShareAlike 4.0 International license, and the underlying code used to format and display that content is licensed under the LGPLv3 by Canonical Ltd.

I think this is for 99% of our sites.

I have added a PR to correct this.

Out of curiousity, what are you looking to use?

**Comment by hwpplayer1** [comment]
@pmahnke Thanks for clarification I am not about using something, I signed Code of Conduct of Ubuntu Community, and I am local team member of Ubuntu Turkey, I just do want to make everything clear and understandble for newcomers and who are fanatic of a point of view, then everything will be "normalized"

LGPL is for libraries also, I thought it was an Affero like all web and cloud services, but I am not talking about that 

Maybe Canonical planned to write a web framework by own effort I am not sure

Content also the one that I am not into like logos or mottos

But I will raise pull requests to offer new features and test this project on my local network

Thanks, see you
