### ISSUE TITLE
Bug with Canonical Careers website

### ISSUE THREAD

**Issue by dhgreen99** [canonical-web-and-design/canonical.com#388]
I am trying to apply to this job:

https://canonical.com/careers/2808065/iot-project-manager-devices-remote

After filling out the form I get a '404 page not found error'.

**Comment by pmahnke** [comment]
@dhgreen99 I think I see you in greenhouse, did it finaly work for you?

We aren't seeing issues, perhaps it was a temporary fault?

**Comment by dhgreen99** [comment]
Please don't worry about it.  A Canonical employee sent me the link and the
job opening may have expired, or have been on an internal website.
My friend sent my resume along and we'll see what happens.

For the record, the original link (that I had been working) is now giving
me a 404 error, so that link is definitely gone.

No worries.
Thanks for the follow up!  Issue closed.

David
