### ISSUE TITLE
all roles counter shows 0

### ISSUE THREAD

**Issue by lechsandecki** [canonical-web-and-design/canonical.com#396]
hi web team!
looks like our all roles counter is showing 0, which is incorrect
![Screenshot from 2021-07-02 14-32-39](https://user-images.githubusercontent.com/55583702/124282228-83c54480-db42-11eb-8cb3-040e33d11526.png)

**Comment by anthonydillon** [comment]
Thanks @lechsandecki, that is certainly not right. We will look into this soon.
