### ISSUE TITLE
Create issue templates for canonical.com

### ISSUE THREAD

**Issue by I-Cat** [canonical-web-and-design/canonical.com#401]
What Did @I-Cat Do?

@I-Cat Steps:     :feet: 
1.  I Visited: https://canonical.com/#partners Website.
2. I clicked on "https://github.com/canonical-web-and-design/canonical.com/issues/new"
3.  It brought me directly to make a new issue and I could not make an edit or a sugestion.

Issue(s): 
1.  There was no Issue template provided
2.  I Could not "Improve this site" (https://canonical.com/#partners) by makeing this issue

Suggestion(s): From @I-Cat  :cat2:  :smile: 

1.  I would like to use a issue template when (someone) makes a new issue to make it more user friendly
2. I would like to beable to click a toggle button and have the white screen portions change from white to a better contrast for people with disabilities​

~ Issue Template: From @I-Cat To You : ~
 
Please tell us Your Issue Below | Suggestions? | Tasks:
------------ | -------------| -------------
bla bla Issue 1 | blah blah Suggestions | - [ ] @mentions, #refs, [links](), **formatting**, and <add>tags</add> supported
bla bla Issue 2 Discription | bla bla Issue 2 Discription | - [x] this is a complete item
bla bla Issue 3 Discription | bla bla Issue 3 Discription | - [ ] this is an incomplete item
 
Thanks :
Sigined off by me: @I-Cat

Ping: @SirSamTumless

**Comment by petesfrench** [comment]
Don't we have an issue template here: https://github.com/canonical-web-and-design/canonical.com/blob/main/.github/pull_request_template.md
