### ISSUE TITLE
Change jaas.ai link to juju.is

### ISSUE THREAD

**Issue by cristinadresch** [canonical-web-and-design/canonical.com#420]
Under juju section on https://canonical.com/#products change link from jaas.ai to juju.is

![Screenshot 2021-09-13 at 14.31.27.png](https://images.zenhubusercontent.com/5c73e557b33938548e4df8a3/5ec5d318-49c7-4333-abe6-ed05897dda72)

**Comment by goulinkh** [comment]
Is it normal that currently https://jaas.is is not reachable ?

**Comment by cristinadresch** [comment]
@goulinkh it's actually https://jaas.ai/
