### ISSUE TITLE
Header too large on small screens

### ISSUE THREAD

**Issue by andesol** [canonical-web-and-design/canonical.com#422]
I didn't know if it was a bug or a feature, but there's no way of collapsing the nav on mobile, so it cover roughly one third of the viewport height.

![image](https://user-images.githubusercontent.com/20623084/133432772-f7bef390-d5c1-4362-9a78-a9a01c40f553.png)

**Comment by SirSamTumless** [comment]
@andesol Thank you for flagging this. We are actually in the middle of exploring different nav types so this will be fixed when we find a solution,
