### ISSUE TITLE
Error when submitting job application

### ISSUE THREAD

**Issue by rochanaw** [canonical-web-and-design/canonical.com#426]
I'm unable to apply for a job vacancy under careers section on canonical.com. I get the error "413 Request Entity Too Large" 

Below is a screenshot of the error

![image](https://user-images.githubusercontent.com/21109249/134119158-53f5a21d-554a-49a6-b798-9b15d978dc3c.png)

**Comment by notcos** [comment]
I am receiving a 404 error when attempting to submit my application at the following URL:
https://canonical.com/careers/3362177/linux-support-associate-home-based-remote
![image](https://user-images.githubusercontent.com/66905097/134194186-fcd94b83-cb83-4326-9c38-7a27c7311f8e.png)

**Comment by cristinadresch** [comment]
@notcos could you try again with a smaller size file? if you're still having an issue let us know

**Comment by sowasred2012** [comment]
Closing, duplicate of https://github.com/canonical-web-and-design/canonical.com/issues/269
