### ISSUE TITLE
Contributor agreement form:

### ISSUE THREAD

**Issue by I-Cat** [canonical-web-and-design/canonical.com#427]
I Went to Download the pdf agreement It pointed me to a in vaild url. 

https://canonical.com/sites/default/files/active/images/Canonical-HA-CLA-ANY-E.pdf?_ga=2.252620111.792236006.1632263893-1149715271.1632263893

**Comment by cristinadresch** [comment]
@I-Cat can you send us the URL where the form is please? Thanks
