### ISSUE TITLE
Can't browse the careers or cube microcert portion of ubunu.com

### ISSUE THREAD

**Issue by vscodr** [canonical-web-and-design/canonical.com#429]
Can't browse the careers or cube micro cert portion of ubuntu.com

I am logged into ubuntu one correctly.

**Comment by anthonydillon** [comment]
Both seem to be working for me. Might have been a short outage. Please reopen if you continue to experience issues.

**Comment by vscodr** [comment]
OK Thanks got in! I really want in on that beta!  :)

Brad
