### ISSUE TITLE
Canonical homepage looks broken on mobile

### ISSUE THREAD

**Issue by grobbie** [canonical-web-and-design/canonical.com#431]
Using Firefox and Chrome on Android, the site looks really odd. The top menu items are stacked and the animation is missing, and there is a large chunk of white space before the above the fold content.

**Comment by SirSamTumless** [comment]
Please provide a screenshot - thanks!

**Comment by grobbie** [comment]
![Screenshot_20210925-105612](https://user-images.githubusercontent.com/3254480/135068004-3293c048-7f72-4219-bcbd-1fd324ff95bd.png)
