### ISSUE TITLE
Stale link to landscape on-prem

### ISSUE THREAD

**Issue by zyga** [canonical-web-and-design/canonical.com#433]
This page:
 - https://help.landscape.canonical.com/FAQ
Links to this page:
 - https://canonical.com/enterprise-services/ubuntu-advantage/landscape/dedicated-edition
Which no longer exists

**Comment by SirSamTumless** [comment]
@pmahnke Is this something you could help out with?

**Comment by sowasred2012** [comment]
@wgx is this something your tribe could help with?

**Comment by pmahnke** [comment]
I think we just need to add a redirect on canonical

http://www.canonical.com/enterprise-services/ubuntu-advantage/landscape/dedicated-edition
should redirect to ubuntu.com/support
