### ISSUE TITLE
error 404 link : https://canonical.com/about-canonical/canonical-and-open-source

### ISSUE THREAD

**Issue by I-Cat** [canonical-web-and-design/canonical.com#445]
### ### error 404
[404 error] (https://canonical.com/about-canonical/canonical-and-open-source)
@canonical-web-and-design
![Screenshot from 2021-11-19 11-20-36](https://user-images.githubusercontent.com/68921721/142656857-38adc09c-da38-4d2f-8b2d-0c9dbf471733.png)

**Comment by sowasred2012** [comment]
Hi, thanks for reporting this - where was this linked from?

**Comment by I-Cat** [comment]
> 
>   ¯\_(๑ ᴗ ๑)_/¯
>  Thats Odd Now I can't refind the link. I Will let you know how I got there I will try to check my browser history.
> Just checked and...
> Now When I go to about canonical It shows me about ubuntu
> When I Go to https://canonical.com/?_ga=2.232419423.1975013869.1637708279-34943818.1637708279
> at the bottom it says leagal ubuntu https://ubuntu.com/legal?_ga=2.244338885.1975013869.1637708279-34943818.1637708279
> Question :  Is the url ment to show Canonical legal ? Or is Ubuntu the owner of canonical
> Thanks -- I-Cat 
:smile_cat:

**Comment by sowasred2012** [comment]
Canonical is the owner of Ubuntu :D

I will close this issue for the time being, if you find the link again let us know and we can reopen this.
