### ISSUE TITLE
Error "413 Request Entity Too Large" When Submitting Job Application

### ISSUE THREAD

**Issue by KillYourFM** [canonical-web-and-design/canonical.com#476]
**Issue**: Pressing the "Submit Application" button on [this](https://canonical.com/careers/3776036) Canonical Careers listing results in error 413 "Request Entity Too Large." (Upload size limits may need to be increased on the server?)

**Expected Result**:  Some type of confirmation page communicating that my application has been sent successfully.

**Supporting Info**:  CV and Cover Letter are in PDF format, and less than 1MB each. 

**URL of Job Posting**: https://canonical.com/careers/3776036

Screenshot attached.
<img width="486" alt="Screen Shot 2022-01-09 at 12 26 01 PM" src="https://user-images.githubusercontent.com/47599547/148680247-a241bc23-f10d-466c-8af5-d9d324660dbc.png">
 Thank you!

**Comment by cristinadresch** [comment]
@tbille any thoughts about this?
