### ISSUE TITLE
Job detail view makes unnecessary call to Greenhouse API

### ISSUE THREAD

**Issue by aqasim23** [canonical-web-and-design/canonical.com#487]
Original issue description by @aqasim23:

"Submit application button is redirected to a page not available on your servers."

---

Investigating this issue, we found we're hitting a rate limit on Greenhouse's API, and there's a call to `harvest.get_departments()` on job detail pages. Job detail pages don't show departments (only the listing index does), so we should update the page to make sure we're _not_ making this call on such pages.

Sentry issue: https://sentry.is.canonical.com/canonical/canonical-com/issues/20073/events/1002450/#exception

**Comment by sowasred2012** [comment]
@aqasim23 thanks for reporting this, we're investigating it now.
