### ISSUE TITLE
Front page has a link to conjure-up.io site, but that redirects to https://juju.is/

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/canonical.com#491]
The front page of canonical.com has a link to conjure-up.io, and features it (along with cloud-init, mir, netplan, etc.). However, this simply redirects to juju.is.

**Comment by cristinadresch** [comment]
Thanks for raising this. We will replace it with a link to charmed-kubeflow.io

**Comment by cristinadresch** [comment]
This is now fixed
