### ISSUE TITLE
Just some suggestions for the website

### ISSUE THREAD

**Issue by Nico870** [canonical-web-and-design/canonical.com#493]
Hi, I have been working on the website for around 15 years. Just reviewed Canonical's website and have some suggestions. 

1. There are some hyperlinks to the other websites. For example, the text "improve this site" on the bottom, it will be better if the websites it lands open new windows, instead of replacing the original website.  It will be earlier for the visitors to stay on Canonical's website. The situation is the same as the links to the partners' websites. 

2. If possible, add hyperlinks to all the partner logos. All those partners have good reputations, to have links to their websites will increase the ranking on organic search. 

3.  Instead of listing the URLs on the websites, change them to the "call to action" button. For example, change "ubuntu.com" to "Check It Now!" It will encourage the visitors to have actions. Then there will be more chances for getting leads. 

4. "Contact Us" is usually very important for visitors. Especially when the sales and support contact windows are under that category. Don't know if it's possible to put it on the top menu. If customers can't find the sales easily, they might just leave. As for the "support", when customers need to contact support, it means they are facing some issues and would like to fix them ASAP. So, making them easy to find the "contact us" page is critical. 

[Suggestion_website.pdf](https://github.com/canonical-web-and-design/canonical.com/files/8084809/Suggestion_website.pdf)

**Comment by sowasred2012** [comment]
Thanks for the suggestions, we'll bear them in mind in our future development.
