### ISSUE TITLE
The "software directory" page is out of date

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/canonical.com#497]
https://canonical.com/projects/directory

MicroK8s was contacted because it isn't listed on this page. The Kubernetes team can supply information to update this, but looking at it, there are a number of key projects not included here and the contact information seems to be out of date for a lot of them

**Comment by cristinadresch** [comment]
@pmahnke do you know if we have the data for this?

**Comment by anthonydillon** [comment]
Sheet to update the content: https://docs.google.com/spreadsheets/d/14Smfpq9ttrPt2jPx70NB3QTixH_6h7Ktnp1CihjT1So/edit#gid=0
