### ISSUE TITLE
[Copy update] Ubuntu IoT and Devices - plans and pricing

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/canonical.com#544]
Ubuntu IoT and Devices - plans and pricing

One new sentence and a few spelling changes.

[Copy doc here](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.2hod1nnqjxno)

**Comment by sowasred2012** [comment]
Just spotted this, we had a request come in for this page via canonical-editors which I've just triaged, so I'll close this issue as a duplicate: https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit#heading=h.j00cl08ux1et
