### ISSUE TITLE
Add search to the careers pages

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/canonical.com#556]
It's common and expected that a careers section of a site would contain a search.

**Comment by carkod** [comment]
I think maybe we should include this in the new launch of c.com? @davegoddard42 @petesfrench

**Comment by davegoddard42** [comment]
@petesfrench @carkod There's still some work to figure out the exact scope but these career changes will probably constitute a roadmap item in their own right. I'm writing the spec currently. Given how slow/delayed c.com v3 is shaping up to be, we shouldn't let that act as a blocker to improvements to canonical.com pages.

**Comment by anthonydillon** [comment]
This is done via https://github.com/canonical-web-and-design/canonical.com/pull/574
