### ISSUE TITLE
Remove the Part Time/Full Time options from the open roles filter

### ISSUE THREAD

**Issue by davegoddard42** [canonical-web-and-design/canonical.com#558]
On the list of [open roles](https://canonical.com/careers/all) there's a filter with some options (Home based, Office based, Management, Full-time, Part-time). We don't have any part time jobs at Canonical, so these should be removed.

![image.png](https://images.zenhubusercontent.com/609106f0180d4707d2eed75a/b1f0b37e-bb68-43a5-bcdb-7cfbeae4aded)

**Comment by minkyngkm** [comment]
This issue has been fixed by this [PR](https://github.com/canonical-web-and-design/canonical.com/pull/557). Just deploying was not made so I just quickly did it. Should be live soon! Thanks Dave 👍
