### ISSUE TITLE
Unexpected menu animation on click (partners)

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/canonical.com#56]
/partners, if you click on 'partners' there is this glitch, that doesn't seem to happen elsewhere:
Video https://drive.google.com/file/d/1DYj70j8wGs4D-TuOZ50DHv7sivo34vs-/view?usp=sharing

**Comment by solazio** [comment]
This bug has been fixed when mega menu navigation was implemented https://github.com/canonical-web-and-design/canonical.com/pull/57. Closing
