### ISSUE TITLE
Ui issue on the footer, can be easily improved

### ISSUE THREAD

**Issue by nwokopresh** [canonical-web-and-design/canonical.com#568]
*Note - filling in this form will file an issue against the canonical.com website*

## Summary
Ui issue on the footer, the list style icon around this improve site is lapping on the text on my iPhone 12promax

## Process
View browser in iPhone 12promax and scroll to footer, minor issue

## Current and expected result
Ui can be easily fixed, it's just a minor ui issue

## Screenshot
![image](https://user-images.githubusercontent.com/91806435/177053609-ed70c4de-af49-49db-b3e4-6cd99c2c1df6.jpeg)

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by sowasred2012** [comment]
Hi, thanks for reporting this - this has [been addressed](https://github.com/canonical-web-and-design/vanilla-framework/issues/4429) in an upstream project, and will be rolled out to this site in the next couple of days.

**Comment by petesfrench** [comment]
Closing as this has now been fixed in the issue mentioned above

**Comment by sowasred2012** [comment]
Closed by https://github.com/canonical-web-and-design/canonical.com/pull/567
