### ISSUE TITLE
Error During submiting the application for job

### ISSUE THREAD

**Issue by Tarique1411** [canonical-web-and-design/canonical.com#569]
Hi there, it always give an error 500 while i am submiting the job application for web developer in Ubuntu website.
Please take a look into it, if it regular happens, then how can apply for the job. I looking for job since long time in ubuntu website, i am php developer work in Core PHP, and it's different types of framework like Laravel and CI.
Please help me to find the job.
Thanks
Regard 
Tarique Anwar.

**Comment by sowasred2012** [comment]
@Tarique1411 thanks for reporting this - it looks like there was an outage on the Greenhouse side (https://status.greenhouse.io/), could you try submitting again and let us know how you get on?

**Comment by petesfrench** [comment]
@tarique1411 we are going to close this for now, if the issue reoccurs can you open a new issue please
