### ISSUE TITLE
"Careers" section

### ISSUE THREAD

**Issue by Iktomist** [canonical-web-and-design/canonical.com#590]
The website says, rather excitingly, "we are hiring." But after clicking the link, one is greeted with a server error.

> 500: Server error
> Something’s gone wrong.
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> Try reloading the page. If the error persists, please note that it may be a [known issue](https://github.com/canonical-web-and-design/canonical.com/issues). If not, please [file a new issue](https://github.com/canonical-web-and-design/canonical.com/issues/new).

**Comment by anthonydillon** [comment]
@Iktomist thank you very much taking the time to report this issue to us.
