### ISSUE TITLE
PAGE BROKE ON SUBMIT

### ISSUE THREAD

**Issue by rikongha** [canonical-web-and-design/canonical.com#600]
https://canonical.com/careers/3290946/junior-devops-engineer-remote

while applying for the above position, upon submitting I get an error 404.

<img width="1726" alt="Screenshot 2022-07-29 at 14 07 43" src="https://user-images.githubusercontent.com/43537915/181766974-4d5a9036-5c0f-43d6-ae33-85ab5ff68f30.png">

**Comment by carkod** [comment]
Hi, thanks for reporting. Seems like it's working now? Let us know if still doesn't work

![junior-devops-role](https://user-images.githubusercontent.com/14939793/182111088-5c167825-dd06-4d6d-92bb-1776c3017354.png)
